### ISSUE TITLE
Phase 1 ToDo

### ISSUE THREAD

**Issue by calebdoxsey** [golang-book/bootcamp-examples#2]
- [ ] Ancestor Keys are wrong
- [ ] Visited links should not be purple
- [ ] Tweets are not limited to 140 characters
- [ ] Usernames should be alphanumeric only and start with a letter, maybe have a dash or underscore
- [ ] Usernames should be limited to a certain size
